
compliments=['You are so pretty',
             'You should be proud of yourself',
             'You are enough',
             'You are so smart',
             'You are awesome!',
              'Your positivity is infectious',
             'You are amazing!',
             'You are a true gift to the people in your life',
             'Your smile makes people smile',
             'Thank you for being such a great person.',
             'You have a remarkable sense of humor.',
            'Thanks for being you!',
'Being around you makes everything better.',
'The world would be a better place if more people were like you!',
'You are one of a kind.',
'You are so strong.',
'You have such a great heart.',
'You are beautiful inside and out.',
'You’ve accomplished so many incredible things.',
'You spark so much joy.',
'Your potential is limitless.',
'You are making a real difference in the world.',
'You’re so unique.',
'You make the small things count.']
             
